version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Africa/Nairobi"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Africa/Nairobi"
